config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
  end
  get 'static_pages/about'
  get 'static_pages/contact'
  root to: 'static_pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  validates :first_name, presence: true
  validates :last_name, presence: true
  before_save :assign_role
  
  
  def assign_role
    self.role = Role.find_by name: "Guest" if self.role.nil?
  end
  
  def admin?
    self.role.name == "Admin"
  end
  
  def coach?
    self.role.name == "Coach"
  end
  
  def athlete?
    self.role.name == "Athlete"
  end
  def guest?
    self.role.name == "Guest"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_user, only: [:show, :edit, :update]
  load_and_authorize_resource
  
  def index
    @users = User.all
  end
  
  def show
    @joined_on = @user.created_at.to_formatted_s(:short)
    if @user.current_sign_in_at
      @last_login = @user.current_sign_in_at.to_formatted_s(:short)
    else
      @last_login = "never"
    end    
  end
  
  def edit
  end
  
  def update
    
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end
  
    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
    end    
    
    if successfully_updated
      flash[:success] = "The user was updated successfully"
      redirect_to users_path
    else
      flash[:danger] = "The user did not update successfully"
      render 'edit'
    end    
  end
  
  
  
  protected
    def needs_password?(user, params)
      params[:password].present?
    end
  
  
  private
    # def set_user
    #   @user = User.find(params[:id])
    # end
    
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
    end

end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :first_name %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :last_name %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  </div>  
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :email %>
    </div>
    <div class="col-md-8">
      <%= f.email_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :role_id %>
    </div>
    <div class="col-md-8">
      <%= collection_select(:user, :role_id, Role.all, :id, :name, { prompt: true }, class: 'form-control') %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :password %>
    </div>
    <div class="col-md-8">
      <%= f.password_field :password, class: 'form-control', placeholder: "Leave blank if unchanged" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-8">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <%= render 'form' %>
      <strong><%= link_to 'Show', @user %></strong> |
      <strong><%= link_to 'Back', users_path %></strong>      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="table-responsive col-md-10">
      <h2>Users</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>First Name</th>
            <th>First Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.first_name, user %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role.name %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      
      <a href="#">Invite new user</a>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <p>
        <strong>First Name:</strong>
        <%= @user.first_name %>
      </p>
      <p>
        <strong>Last Name:</strong>
        <%= @user.last_name %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>Role:</strong>
        <%= @user.role.name %>
      </p>
            
      <p>
        <strong>Joined on:</strong>
        <%= @joined_on %>
      </p>
      <p>
        <strong>Last logged in on:</strong>
        <%= @last_login %>
      </p>
      <p>
        <strong>No. times logged in:</strong>
        <%= @user.sign_in_count %>
      </p>      
      
      <strong><%= link_to 'Edit', edit_user_path(@user) %></strong> | 
      <strong><%= link_to 'Back', users_path %></strong>
    </div>
  </div>
</div>