config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
  end
  get 'static_pages/about'
  get 'static_pages/contact'
  root to: 'static_pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    @roles = Role.all
  end
  
  def show
    if @role.users.length == 0
      @assosciated_users = "None"
    else
      @assosciated_users = @role.users.map(&:first_name).join(", ")
    end    
  end
  
  def new
    # @role = Role.new
  end
  
  def create
    # @role = Role.new(role_params)
    
    if @role.save
      flash[:success] = "The role was saved successfully"
      redirect_to roles_path
    else
      flash[:danger] = "The role did not save successfully"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @role.update(role_params)
      flash[:success] = "The role was updated successfully"
      redirect_to roles_path
    else
      flash[:danger] = "The role did not update successfully"
      render 'edit'
    end
  end
  
  def destroy
    @role.destroy
    flash[:success] = "Role was successfully deleted."
    redirect_to roles_path
  end
  
  
  
  private
    def role_params
      params.require(:role).permit(:name, :description)
    end
    
    # def set_role
    #   @role = Role.find(params[:id])
    # end
end

app/views/roles/_form.html.erb
<%= form_for(@role, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>
      <ul>
        <% @role.error.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :name %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :description %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-8">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
  
<% end %>

app/views/roles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2>Edit Role</h2>
      <%= render 'form' %>
      <strong><%= link_to 'Show', @role %></strong> |
      <strong><%= link_to 'Back', roles_path %></strong>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="container">
  <div class="row">
    <div class="table-responsive col-md-10">
      <h2>Roles</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td><%= link_to role.name, role %></td>
            <td><%= role.description %></td>
            <td><%= link_to 'Edit', edit_role_path(role) %></td>
            <td><%= link_to 'Delete', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      
      <%= link_to 'New Role', new_role_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2>New Role</h2>
      <%= render 'form' %>
      <strong><%= link_to 'Back', roles_path %></strong>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <p>
        <strong>Name:</strong>
        <%= @role.name %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @role.description %>
      </p>
      
      <hr/>
      
      <p>
        <strong>Assosciated users:</strong>
        <%= @assosciated_users %>
      </p>
      
      <strong><%= link_to 'Edit', edit_role_path(@role) %></strong> | 
      <strong><%= link_to 'Back', roles_path %></strong>
    </div>
  </div>
</div>